### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by monte-hayward** [smelc/srtcheck#1]
```
python srtcheck.py tests/test1.shouldpass.withwarning.online.734.srt
Traceback (most recent call last):
  File "srtcheck.py", line 182, in <module>
    checkfile(desired_encoding)
  File "srtcheck.py", line 132, in checkfile
    filehandler = open(filename, 'r',encoding=desired_encoding)
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by smelc** [comment]
What version of python are you using ? the `encoding` parameter has been introduced in python 3 if I recall correctly. Could that be the problem ?
